### ISSUE TITLE
First Release Checklist

### ISSUE THREAD

**Issue by kmccullen97** [kmccullen97/terminal-kanban#25]
These are the lasts tasks to do before the first release.
- [ ] Add screen shot of working app
- [ ] Improve documentation
  - [ ] Update features list in README.md
  - [ ] Add tutorial documentation
  - [ ] Run all generate-docs
  - [ ] Improve development setup instructions
  - [ ] Installation instructions
- [ ] Reduce pyinstaller package size (exclude files ect)
